[build]
publish = "public"
command = "./ssg-build.sh"
[[redirects]]
  from = "https://arpit-goyal.netlify.com/*"
  to = "https://arpitgoyal.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.arpitgoyal.com/about/"
  to = "https://arpitgoyal.com/about/"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.arpitgoyal.com/contact/"
  to = "https://arpitgoyal.com/contact/"
  status = 301
  force = true
[[redirects]]
  from = "https://arpitgoyal.com/work"
  to = "https://arpitgoyal.com/work-portfolio"
  status = 301
  force = true
[[redirects]]
  from = "https://blog.arpitgoyal.com/*"
  to = "https://arpitgoyal.com/blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://blog.arpitgoyal.com/*"
  to = "https://arpitgoyal.com/blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/resume"
  to = "https://drive.google.com/file/d/0B1pz4JVn5F_9QVR4NkRCTEowUmM/view?usp=drive_link&resourcekey=0-kmqmOpYeJtpraP64pyCklw"
  status = 200
  force = true
