---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: Title
  description: The title of the post.
  config:
    required: true
- type: text
  name: subtitle
  label: Subtitle
  description: The text shown just below the post title.
- name: tags
  type: tag_list
  default: []
  label: Tags
- type: datetime
  name: date
  label: Date
  config:
    required: true
- type: file
  name: thumb_img_path
  label: Featured Image
  description: The image shown in the blog feed.
- type: file
  name: content_img_path
  label: Alternative Featured Image
  description: The image shown in the single post.
- type: text
  name: excerpt
  label: Excerpt
  description: The excerpt of the post displayed in the blog feed.
- type: text
  name: template
  label: Template
  hidden: true
  default: post
  config:
    required: true
- name: is_external
  type: boolean
  label: Is external
  description: Is this post a link to an external post(true by default)
  default: false
- name: url
  type: text
  config:
    required: false
  label: URL
  description: URL of External post
- name: is_featured
  type: boolean
  label: Is Featured
  description: Is this post the featured post
pages:
- src/pages/products/building-a-mvp.md
- src/pages/products/wireframe-and-prototype.md
- src/pages/products/sketching.md
- src/pages/products/design-fundamentals.md
- src/pages/products/product-artifacts.md
- src/pages/products/contextual-inquiry.md
- src/pages/products/survey-a-survey-to-understand-user-needs-in-furniture-rental-space.md
- src/pages/products/survey-for-furniture-rental-industry.md
