---
label: Product Portfolio
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: The title of the page.
  config:
    required: true
- name: excerpt
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Excerpt
  description: Meta Description
- type: blocks
  name: sections
  label: Sections
  description: Home page sections
  template_types:
  - intro
- type: text
  name: template
  label: Template
  hidden: true
  default: product-portfolio
  config:
    required: true
pages:
- src/pages/product-portfolio.md
